ifndef::imagesdir[:imagesdir: ./../../images]

= Report status query

The technical processing status of a submitted report can be queried based on the transaction identifier.

== HTTP request
The report status is queried via an HTTP GET request with the following settings:

* *URL:* `https://api-dacentral.nav.gov.hu/dcc/m2m/dac9/globaltax/report/{globalTaxReportId}/status`
* *HTTP method:* GET
* *Headers:*
** `Authorization: Bearer {access_token}`
** `Accept: text/xml or application/xml`

== Response: ReportStatusResponse

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<ns2:ReportStatusResponse xmlns="http://schemas.nav.gov.hu/NTCA/2.0/common/service"
    xmlns:ns2="http://schemas.nav.gov.hu/DCC/1.0/m2m/dac9/globaltax/globaltaxapi">
    <context>
        <requestId>019cf6ac-b11c-74b6-8b8c-0832f6805328</requestId>
        <timestamp>2026-03-16T12:43:58.620345274Z</timestamp>
    </context>
    <resultCode>SUCCESS</resultCode>
    <ns2:reportStatus>
        <ns2:status>VALID</ns2:status>
    </ns2:reportStatus>
</ns2:ReportStatusResponse>
----

.Possible statuses and actions
[cols="1,3"]
|===
| Status | Action

| `UPLOADED`
| The report has been uploaded. Wait and query the status again.

| `VALIDATING`
| The report is being validated. Wait and query the status again.

| `VALID`
| The report is valid, technically processed successfully. No further action required.

| `INVALID`
| The report is invalid. Check the `errorCode` and `anomaly` fields
  to identify the cause of the error, then fix and resubmit the report.
|===

.Example: Invalid report response
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<ns2:ReportStatusResponse xmlns="http://schemas.nav.gov.hu/NTCA/2.0/common/service"
    xmlns:ns2="http://schemas.nav.gov.hu/DCC/1.0/m2m/dac9/globaltax/globaltaxapi">
    <context>
        <requestId>019cf6ac-b11c-74b6-8b8c-0832f6805328</requestId>
        <timestamp>2026-03-16T12:43:58.620345274Z</timestamp>
    </context>
    <resultCode>SUCCESS</resultCode>
    <ns2:reportStatus>
        <ns2:status>INVALID</ns2:status>
        <ns2:errorCode>INVALID_FILE</ns2:errorCode>
        <ns2:anomaly>
            <field>exampleField</field>
            <error>Invalid value in column 12, line 34</error>
            <lineNumber>34</lineNumber>
            <columnNumber>12</columnNumber>
        </ns2:anomaly>
        <ns2:anomaly>
            <error>Another error without line and column information</error>
        </ns2:anomaly>
    </ns2:reportStatus>
</ns2:ReportStatusResponse>
----
