ifndef::imagesdir[:imagesdir: ./../../images]

= DAC9 GlobalTaxRequest report submission

With the access token in hand, the DAC-9 global minimum tax report can be submitted.

== HTTP request
The report is submitted via an HTTP POST request with the following settings:

* *URL:* `https://api-dacentral.nav.gov.hu/dcc/v1/m2m/dac9/globaltax/report`
* *HTTP method:* POST
* *Headers:*
** `Authorization: Bearer {access_token}`
** `Content-Type: multipart/form-data`
** `Accept: text/xml or application/xml`
* *Body:* Two-part multipart/form-data:
** `metadata` - The XML representation of `GlobalTaxRequest`
*** `Content-Type: application/xml`
** `report` - The report file (https://www.oecd.org/en/publications/globe-information-return-pillar-two-xml-schema_c594935a-en.html[GloBE Information Return (Pillar Two) XML Schema]).
*** `Content-Type: application/octet-stream`
*** If the file is not compressed, it must be sent as plaintext XML
*** If the file is compressed (gzip), the compressed raw binary stream must be sent.
*** The maximum allowable file size is 100 MB (both compressed and uncompressed). If the file is compressed, the size of the decompressed content must not exceed 250 MB.
** Character encoding is UTF-8 in all cases
** When submitting, the CRC32 checksum of the file content must also be provided in the `reportChecksum` field. If the file is compressed, the CRC32 value of the decompressed content must be provided.

== Request: GlobalTaxRequest

[source,xml]
----
<ns2:GlobalTaxRequest xmlns="http://schemas.nav.gov.hu/NTCA/2.0/common/service"
    xmlns:ns2="http://schemas.nav.gov.hu/DCC/1.0/m2m/dac9/globaltax/globaltaxapi">
    <context>
        <requestId>019ce6cd-394b-7622-9c01-6880b92f086d</requestId>
        <timestamp>2026-03-13T10:45:35.180339322Z</timestamp>
    </context>
    <ns2:compressedContent>false</ns2:compressedContent>
    <ns2:reportType>GLOBE_OECD_V1</ns2:reportType>
    <ns2:reportChecksum cryptoType="CRC32">639479525</ns2:reportChecksum>
</ns2:GlobalTaxRequest>
----

.Request fields
[cols="1,3,1"]
|===
| Field | Description | Required

| `compressedContent`
| `true` if the submitted content is compressed, `false` otherwise
| Yes

| `reportType`
| The report type. Currently the only allowed value is: `GLOBE_OECD_V1`
| Yes

| `reportChecksum`
| The checksum of the report (`CryptoType`). For compressed content,
  the checksum of the *decompressed* content must be provided.
| Yes
|===

== Response: GlobalTaxResponse

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<ns2:GlobalTaxResponse xmlns="http://schemas.nav.gov.hu/NTCA/2.0/common/service"
    xmlns:ns2="http://schemas.nav.gov.hu/DCC/1.0/m2m/dac9/globaltax/globaltaxapi">
    <context>
        <requestId>019ce6cd-394b-7622-9c01-6880b92f086d</requestId>
        <timestamp>2026-03-13T10:45:35.180339322Z</timestamp>
    </context>
    <resultCode>SUCCESS</resultCode>
    <ns2:globalTaxReportId>019ce6cd-4540-78a7-ac4f-5049465a1fa0</ns2:globalTaxReportId>
</ns2:GlobalTaxResponse>
----

.Response fields
[cols="1,3"]
|===
| Field | Description

| `globalTaxReportId`
| The unique transaction identifier of the submitted report.
  This identifier is required to query the report status.
|===
