ifndef::imagesdir[:imagesdir: ./../../images]

= DAC8 CarfRequest jelentés beküldés

A hozzáférési token birtokában a DAC-8 CARF (Crypto-Asset Reporting Framework) jelentés küldhető be.

== Http kérés
A jelentés beküldése HTTP POST kéréssel történik, ahol a következő beállítások szükségesek:

* *Base URL:*
** Éles: `https://api-dacentral.nav.gov.hu`
** Teszt: `https://api-dacentral-test.nav.gov.hu`
* *Path:* `/dcc/m2m/v1/dac8/carf/report`
* *HTTP metódus:* POST
* *Fejlécek:*
** `Authorization: Bearer {access_token}`
** `Content-Type: multipart/form-data`
** `Accept: text/xml vagy application/xml`
* *Törzs:* Két részből álló multipart/form-data:
** `metadata` - A `CarfRequest` XML reprezentációja
*** `Content-Type: application/xml`
** `report` - A jelentés fájlja (https://www.oecd.org/en/publications/crypto-asset-reporting-framework-xml-schema_578052ec-en/support-materials.html[Crypto-Asset Reporting Framework (CARF) XML Schema]).
*** `Content-Type: application/octet-stream`
*** Ha a fájl nem tömörített, akkor plaintext XML-ben kell küldeni
*** Ha a fájl tömörített (gzip), akkor tömörítés nyers binary stream-ben kell küldeni.
*** A befogadható fájl maximális mérete: 100 MB (tömörített és nem tömörített formában). Ha a fájl tömörített, akkor a kitömörített tartalom mérete nem haladhatja meg a 250 MB-ot.
** Minden esetben a karakter kódolás UTF-8
** Beküldéskor a fájl tartalmának CRC32 ellenőrző összegét is meg kell adni a `reportChecksum` mezőben. Ha a fájl tömörített, akkor a kitömörített tartalom CRC32 értékét kell megadni.

== Kérés: CarfRequest

[source,xml]
----
<ns2:CarfRequest xmlns="http://schemas.nav.gov.hu/NTCA/2.0/common/service"
    xmlns:ns2="http://schemas.nav.gov.hu/DCC/1.0/m2m/dac8/carf/carfapi">
    <context>
        <requestId>01a05da9-d9a9-7c41-ad31-fcdd4fc3066f</requestId>
        <timestamp>2026-09-01T15:50:07.531273284Z</timestamp>
    </context>
    <ns2:compressedContent>false</ns2:compressedContent>
    <ns2:reportType>CARF_OECD_V1_5</ns2:reportType>
    <ns2:reportChecksum cryptoType="CRC32">891091852</ns2:reportChecksum>
</ns2:CarfRequest>
----

.Kérés mezők
[cols="1,3,1"]
|===
| Mező | Leírás | Kötelező

| `compressedContent`
| `true` ha a beküldött tartalom tömörített, `false` egyébként
| Igen

| `reportType`
| A jelentés típusa. Jelenleg az egyetlen megengedett érték: `CARF_OECD_V1_5`
| Igen

| `reportChecksum`
| A jelentés ellenőrző összege (`CryptoType`). Tömörített tartalom esetén
  a *kitömörített* tartalom ellenőrző összegét kell megadni.
| Igen
|===

== Válasz: CarfResponse

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<ns2:CarfResponse xmlns="http://schemas.nav.gov.hu/NTCA/2.0/common/service"
    xmlns:ns2="http://schemas.nav.gov.hu/DCC/1.0/m2m/dac8/carf/carfapi">
    <context>
        <requestId>01a05da9-d9a9-7c41-ad31-fcdd4fc3066f</requestId>
        <timestamp>2026-09-01T15:50:07.531273284Z</timestamp>
    </context>
    <resultCode>SUCCESS</resultCode>
    <ns2:carfReportId>01a05d95-016f-7747-9a01-2180d7307079</ns2:carfReportId>
</ns2:CarfResponse>
----

.Válasz mezők
[cols="1,3"]
|===
| Mező | Leírás

| `carfReportId`
| A beküldött jelentés egyedi tranzakció azonosítója.
  Ez az azonosító szükséges a jelentés állapotának lekérdezéséhez.
|===
