ifndef::imagesdir[:imagesdir: ./../../images]

= DAC8 CarfRequest report submission

With the access token in hand, the DAC-8 CARF (Crypto-Asset Reporting Framework) report can be submitted.

== HTTP request
The report is submitted via an HTTP POST request with the following settings:

* *Base URL:*
** Prod: `https://api-dacentral.nav.gov.hu`
** Test: `https://api-dacentral-test.nav.gov.hu`
* *Path:* `/dcc/m2m/v1/dac8/carf/report`
* *HTTP method:* POST
* *Headers:*
** `Authorization: Bearer {access_token}`
** `Content-Type: multipart/form-data`
** `Accept: text/xml or application/xml`
* *Body:* Two-part multipart/form-data:
** `metadata` - The XML representation of `CarfRequest`
*** `Content-Type: application/xml`
** `report` - The report file (https://www.oecd.org/en/publications/crypto-asset-reporting-framework-xml-schema_578052ec-en/support-materials.html[Crypto-Asset Reporting Framework (CARF) XML Schema]).
*** `Content-Type: application/octet-stream`
*** If the file is not compressed, it must be sent as plaintext XML
*** If the file is compressed (gzip), the compressed raw binary stream must be sent.
*** The maximum allowable file size is 100 MB (both compressed and uncompressed). If the file is compressed, the size of the decompressed content must not exceed 250 MB.
** Character encoding is UTF-8 in all cases
** When submitting, the CRC32 checksum of the file content must also be provided in the `reportChecksum` field. If the file is compressed, the CRC32 value of the decompressed content must be provided.

== Request: CarfRequest

[source,xml]
----
<ns2:CarfRequest xmlns="http://schemas.nav.gov.hu/NTCA/2.0/common/service"
    xmlns:ns2="http://schemas.nav.gov.hu/DCC/1.0/m2m/dac8/carf/carfapi">
    <context>
        <requestId>01a05da9-d9a9-7c41-ad31-fcdd4fc3066f</requestId>
        <timestamp>2026-09-01T15:50:07.531273284Z</timestamp>
    </context>
    <ns2:compressedContent>false</ns2:compressedContent>
    <ns2:reportType>CARF_OECD_V1_5</ns2:reportType>
    <ns2:reportChecksum cryptoType="CRC32">891091852</ns2:reportChecksum>
</ns2:CarfRequest>
----

.Request fields
[cols="1,3,1"]
|===
| Field | Description | Required

| `compressedContent`
| `true` if the submitted content is compressed, `false` otherwise
| Yes

| `reportType`
| The report type. Currently the only allowed value is: `CARF_OECD_V1_5`
| Yes

| `reportChecksum`
| The checksum of the report (`CryptoType`). For compressed content,
  the checksum of the *decompressed* content must be provided.
| Yes
|===

== Response: CarfResponse

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<ns2:CarfResponse xmlns="http://schemas.nav.gov.hu/NTCA/2.0/common/service"
    xmlns:ns2="http://schemas.nav.gov.hu/DCC/1.0/m2m/dac8/carf/carfapi">
    <context>
        <requestId>01a05da9-d9a9-7c41-ad31-fcdd4fc3066f</requestId>
        <timestamp>2026-09-01T15:50:07.531273284Z</timestamp>
    </context>
    <resultCode>SUCCESS</resultCode>
    <ns2:carfReportId>01a05d95-016f-7747-9a01-2180d7307079</ns2:carfReportId>
</ns2:CarfResponse>
----

.Response fields
[cols="1,3"]
|===
| Field | Description

| `carfReportId`
| The unique transaction identifier of the submitted report.
  This identifier is required to query the report status.
|===
