ifndef::imagesdir[:imagesdir: ./../../images]

= DAC8 Jelentés státusz lekérdezés

A beküldött jelentés technikai feldolgozási állapota a tranzakció azonosító alapján lekérdezhető.

== Http kérés
A jelentés állapotának lekérdezése HTTP GET kéréssel történik, ahol a következő beállítások szükségesek:

* *Base URL:*
** Éles: `https://api-dacentral.nav.gov.hu`
** Teszt: `https://api-dacentral-test.nav.gov.hu`
* *Path:* `/dcc/m2m/v1/dac8/carf/report/{carfReportId}/status`
* *HTTP metódus:* GET
* *Fejlécek:*
** `Authorization: Bearer {access_token}`
** `Accept: text/xml vagy application/xml`

== Válasz: ReportStatusResponse

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<ns2:ReportStatusResponse xmlns="http://schemas.nav.gov.hu/NTCA/2.0/common/service"
    xmlns:ns2="http://schemas.nav.gov.hu/DCC/1.0/m2m/dac8/carf/carfapi">
    <context>
        <requestId>01a05da9-d9a9-7c41-ad31-fcdd4fc3066f</requestId>
        <timestamp>2026-09-01T15:50:07.531273284Z</timestamp>
    </context>
    <resultCode>SUCCESS</resultCode>
    <ns2:reportStatus>
        <ns2:status>VALID</ns2:status>
    </ns2:reportStatus>
</ns2:ReportStatusResponse>
----

.Lehetséges státuszok és teendők
[cols="1,3"]
|===
| Státusz | Teendő

| `UPLOADED`
| A jelentés feltöltésre került. Várjon, majd kérdezze le újra a státuszt.

| `VALIDATING`
| A jelentés ellenőrzés alatt áll. Várjon, majd kérdezze le újra a státuszt.

| `VALID`
| A jelentés érvényes, technikailag sikeresen feldolgozásra került.

| `APPROVED`
| A jelentést a felhasználó jóváhagyta. Nincs szükség további teendőre.

| `DECLINED`
| A jelentést a felhasználó elutasította. Nincs szükség további teendőre.

| `INVALID`
| A jelentés érvénytelen. Ellenőrizze az `errorCode` és `anomaly` mezőket
  a hiba okának azonosításához, majd javítsa és küldje be újra a jelentést.
|===

.Példa: Érvénytelen jelentés válasz
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<ns2:ReportStatusResponse xmlns="http://schemas.nav.gov.hu/NTCA/2.0/common/service"
    xmlns:ns2="http://schemas.nav.gov.hu/DCC/1.0/m2m/dac8/carf/carfapi">
    <context>
        <requestId>01a05da9-d9a9-7c41-ad31-fcdd4fc3066f</requestId>
        <timestamp>2026-09-01T15:50:07.531273284Z</timestamp>
    </context>
    <resultCode>SUCCESS</resultCode>
    <ns2:reportStatus>
        <ns2:status>INVALID</ns2:status>
        <ns2:errorCode>INVALID_FILE</ns2:errorCode>
        <ns2:anomaly>
            <field>exampleField</field>
            <error>Invalid value in column 12, line 34</error>
            <lineNumber>34</lineNumber>
            <columnNumber>12</columnNumber>
        </ns2:anomaly>
        <ns2:anomaly>
            <error>Another error without line and column information</error>
        </ns2:anomaly>
    </ns2:reportStatus>
</ns2:ReportStatusResponse>
----
