= Autentikáció - Token igénylés

Az M2M kommunikáció első lépése a hozzáférési token igénylése a Token API-n keresztül.

== Http kérés
A hozzáférési token igénylése HTTP POST kéréssel történik, ahol a következő beállítások szükségesek:

* *URL:* `https://api-dacentral.nav.gov.hu/dcc/m2m/token`
* *HTTP metódus:* POST
* TLS 1.3 vagy újabb verzió használata kötelező
* *Fejlécek:*
** `Accept: text/xml vagy application/xml`

== Kérés: M2MTokenRequest

A kérés az NTCA `AuthRequestType` kiterjesztése, amely tartalmazza a standard
hitelesítési fejlécet, felhasználói adatokat és szoftver azonosítót.

.M2MTokenRequest XML példa
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<ns3:M2MTokenRequest xmlns="http://schemas.nav.gov.hu/NTCA/2.0/common/service" xmlns:ns2="http://schemas.nav.gov.hu/NTCA/2.0/common/authservice"
    xmlns:ns3="http://schemas.nav.gov.hu/DCC/1.0/m2m/token/tokenapi">
    <context>
        <requestId>019ce6a6-2a0c-7207-b3f4-cc8373579c7c</requestId>
        <timestamp>2026-03-13T10:02:55.37291704Z</timestamp>
    </context>
    <ns2:auth>
        <ns2:login>m2m_user_example</ns2:login>
        <ns2:passwordHash cryptoType="SHA-512">5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8</ns2:passwordHash>
        <ns2:taxNumber>12345678</ns2:taxNumber>
        <ns2:predecessorTaxNumber></ns2:predecessorTaxNumber>
        <ns2:requestSignature cryptoType="SHA3-512">12345898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d185255</ns2:requestSignature>
    </ns2:auth>
    <ns2:requestVersion>1.0</ns2:requestVersion>
    <ns2:headerVersion>1.0</ns2:headerVersion>
</ns3:M2MTokenRequest>
----

== Válasz: M2MTokenResponse

Sikeres hitelesítés esetén a válasz tartalmazza a hozzáférési tokent és annak lejárati időpontját.

.M2MTokenResponse XML példa
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<ns3:M2MTokenResponse xmlns="http://schemas.nav.gov.hu/NTCA/2.0/common/service" xmlns:ns2="http://schemas.nav.gov.hu/NTCA/2.0/common/authservice"
    xmlns:ns3="http://schemas.nav.gov.hu/DCC/1.0/m2m/token/tokenapi">
    <context>
        <requestId>019ce66a-c965-74cd-9795-1102575b62b7</requestId>
        <timestamp>2026-03-13T08:58:04.006840049Z</timestamp>
    </context>
    <resultCode>SUCCESS</resultCode>
    <ns3:accessToken>eyJhbGciOiJIUzI1NiIsInR5cC... JWT token</ns3:accessToken>
    <ns3:accessTokenExpiryAt>2026-03-13T13:59:07.478552281Z</ns3:accessTokenExpiryAt>
</ns3:M2MTokenResponse>
----

.Válasz mezők
[cols="1,2,1"]
|===
| Mező | Leírás | Típus

| `accessToken`
| A hozzáférési token értéke, amelyet a későbbi API hívásokhoz kell használni
| `GenericIdType`

| `accessTokenExpiryAt`
| A token lejárati időpontja (UTC, ezredmásodperc pontossággal)
| `GenericTimestampMilliType`
|===

IMPORTANT: A tokent a lejárati időpont előtt kell megújítani.
A lejárt tokennel küldött kérések elutasításra kerülnek.
