ifndef::imagesdir[:imagesdir: ./../images]

= Autentikáció - Token igénylés

Az M2M kommunikáció első lépése a hozzáférési token igénylése a Token API-n keresztül.

== Http kérés
A hozzáférési token igénylése HTTP POST kéréssel történik, ahol a következő beállítások szükségesek:

* *URL:* `https://api-dacentral.nav.gov.hu/dcc/m2m/token`
* *HTTP metódus:* POST
* *Fejlécek:*
** `Content-Type: text/xml vagy application/xml`
** `Accept: text/xml vagy application/xml`

== Kérés: M2MTokenRequest

A kérés az NTCA `AuthRequestType` kiterjesztése, amely tartalmazza a standard
hitelesítési fejlécet, felhasználói adatokat és szoftver azonosítót.

.M2MTokenRequest XML példa
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<ns3:M2MTokenRequest xmlns="http://schemas.nav.gov.hu/NTCA/2.0/common/service" xmlns:ns2="http://schemas.nav.gov.hu/NTCA/2.0/common/authservice"
    xmlns:ns3="http://schemas.nav.gov.hu/DCC/1.0/m2m/token/tokenapi">
    <context>
        <requestId>019ce6a6-2a0c-7207-b3f4-cc8373579c7c</requestId>
        <timestamp>2026-03-13T10:02:55.37291704Z</timestamp>
    </context>
    <ns2:auth>
        <ns2:login>m2m_user_example</ns2:login> <1>
        <ns2:passwordHash cryptoType="SHA-512">12B03226A6D8BE9C6E8CD5E55DC6C7920CAAA39DF14AAB92D5E3EA9340D1C8A4D3D0B8E4314F1F6EF131BA4BF1CEB9186AB87C801AF0D5C95B1BEFB8CEDAE2B9</ns2:passwordHash> <2>
        <ns2:taxNumber>12345678</ns2:taxNumber> <3>
        <ns2:predecessorTaxNumber></ns2:predecessorTaxNumber> <4>
        <ns2:requestSignature cryptoType="SHA3-512">6498E406186580DA6403680FD3A6A008FD7F207CA2AFDE5885C38AC700A9A52A3BAADEE914FA0649DBBE103D2D6E99B1236DA403CDD5EF338245A4474770D591</ns2:requestSignature> <5>
    </ns2:auth>
    <ns2:requestVersion>1.0</ns2:requestVersion> <6>
    <ns2:headerVersion>1.0</ns2:headerVersion> <7>
</ns3:M2MTokenRequest>
----
<1> A `login` tag a technikai felhasználó nevét tartalmazza.
A login nevet a rendszer véletlenszerűen generálja a technikai felhasználó létrehozásakor 15 karakter hosszan.
A login tag az authentikáció egyik eleme.
<2> A `passwordHash` a login tagban szereplő technikai felhasználó jelszavának *nagybetűs* SHA-512 hash értéke.
A literál jelszót a technikai felhasználót létrehozó elsődleges felhasználó adja meg az Online Számla webfelületen.
A passwordHash az authentikáció egyik eleme.
Egyetlen elfogadott értéke: SHA-512.
<3> A `taxNumber` azon adózó adószámának első 8 száma, aki nevében a technikai felhasználó tevékenykedik, és akihez tartozik.
Csak magyar adószám az elfogadott.
<4> A `predecessorTaxNumber` amennyiben megadásra kerül, akkor validálásra kerül,
hogy a taxNumber tagben megadott adózóval jogelőd viszonyban áll-e.
A jogelőd viszony rekurzívan kerül ellenőrzésre, közvetett jogelőd megadása is elfogadott.
A predecessorTaxNumber megadása befolyásolja az operációk üzleti logikáját.
<5> A `requestSignature` a kliens által generált aláírása az üzenetnek.
Minden kéréshez kötelezően tartoznia kell egy requestSignature-nek.
A szerver a kérésben szereplő adatok alapján elvégzi a saját requestSignature számítását és csak akkor hajtja végre a kérést,
ha a tárolt és kapott adatokból a helyes érték ténylegesen előállítható.
A requestSignature számításáról a „requestSignature számítása” fejezet nyújt tájékoztatást.
Egyetlen elfogadott értéke: SHA3-512.
<6> A `requestVersion` a kérés verzióját jelöli, nem kötelező - ilyenkor a rendszer "1.0" értéket fog kezelni. Jelenleg csak a "1.0" érték fogadható el.
<7> A `headerVersion` a fejléc verzióját jelöli, nem kötelező - ilyenkor a rendszer "1.0" értéket fog kezelni. Jelenleg csak a "1.0" érték fogadható el.

=== requestSignature számítására
A `requestSignature` az interfész-authentikáció egyik fő eleme.
A szerepe, hogy illetéktelenek ne tudjanak a rendszerben változtatásokat végrehajtani.
A hash értéket a szerver oldal minden operáció minden kérésénél ellenőrzi,
és csak akkor hajtja végre a műveletet, ha a tárolt és kapott adatokból a helyes érték ténylegesen előállítható.

A `requestSignature` számítására a következő mezők értékeinek konkatenációjával történik, sorrendben:

. requestId értéke (esetünkben "019ce6a6-2a0c-7207-b3f4-cc8373579c7c")
. a timestamp tag értéke "yyyyMMddHHmmss" maszkkal, UTC időben (esetünkben "20260313100255")
. a technikai felhasználó aláírókulcsának literál értéke (technikai felhasználó létrehozásakor megadott érték).
Példához ennek legyen az értéke "ce-8f5e-215119fa7dd621DLMRHRLH2S"

Az így és sorrendben konkatenált string SHA3-512 hash nagybetűsített eredménye lesz a `requestSignature` értéke.

.algoritmus
[source,text]
----
requestSignature = SHA3-512(requestId + timestamp + signingKey).UPPERCASE()

requestSignature = SHA3-512(019ce6a6-2a0c-7207-b3f4-cc8373579c7c + 20260313100255 + ce-8f5e-215119fa7dd621DLMRHRLH2S).UPPERCASE()

requestSignature = SHA3-512(019ce6a6-2a0c-7207-b3f4-cc8373579c7c20260313100255ce-8f5e-215119fa7dd621DLMRHRLH2S).UPPERCASE()

requestSignature = 6498e406186580da6403680fd3a6a008fd7f207ca2afde5885c38ac700a9a52a3baadee914fa0649dbbe103d2d6e99b1236da403cdd5ef338245a4474770d591.UPPERCASE()

requestSignature = 6498E406186580DA6403680FD3A6A008FD7F207CA2AFDE5885C38AC700A9A52A3BAADEE914FA0649DBBE103D2D6E99B1236DA403CDD5EF338245A4474770D591
----

== Válasz: M2MTokenResponse

Sikeres hitelesítés esetén a válasz tartalmazza a hozzáférési tokent és annak lejárati időpontját.

.M2MTokenResponse XML példa
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<ns3:M2MTokenResponse xmlns="http://schemas.nav.gov.hu/NTCA/2.0/common/service" xmlns:ns2="http://schemas.nav.gov.hu/NTCA/2.0/common/authservice"
    xmlns:ns3="http://schemas.nav.gov.hu/DCC/1.0/m2m/token/tokenapi">
    <context>
        <requestId>019ce66a-c965-74cd-9795-1102575b62b7</requestId>
        <timestamp>2026-03-13T08:58:04.006840049Z</timestamp>
    </context>
    <resultCode>SUCCESS</resultCode>
    <ns3:accessToken>eyJhbGciOiJIUzI1NiIsInR5cC... JWT token</ns3:accessToken>
    <ns3:accessTokenExpiryAt>2026-03-13T13:59:07.478552281Z</ns3:accessTokenExpiryAt>
</ns3:M2MTokenResponse>
----

.Válasz mezők
[cols="1,2,1"]
|===
| Mező | Leírás | Típus

| `accessToken`
| A hozzáférési token értéke, amelyet a későbbi API hívásokhoz kell használni
| `GenericIdType`

| `accessTokenExpiryAt`
| A token lejárati időpontja (UTC, ezredmásodperc pontossággal)
| `GenericTimestampMilliType`
|===

IMPORTANT: A tokent a lejárati időpont előtt kell megújítani.
A lejárt tokennel küldött kérések elutasításra kerülnek.
