ifndef::imagesdir[:imagesdir: ./../images]

= Authentication - Token request

The first step in M2M communication is requesting an access token through the Token API.

== HTTP request
The access token is requested via an HTTP POST request with the following settings:

* *URL:* `https://api-dacentral.nav.gov.hu/dcc/m2m/token`
* *HTTP method:* POST
* *Headers:*
** `Content-Type: text/xml or application/xml`
** `Accept: text/xml or application/xml`

== Request: M2MTokenRequest

The request is an extension of the NTCA `AuthRequestType`, which contains the standard
authentication header, user data, and software identifier.

.M2MTokenRequest XML example
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<ns3:M2MTokenRequest xmlns="http://schemas.nav.gov.hu/NTCA/2.0/common/service" xmlns:ns2="http://schemas.nav.gov.hu/NTCA/2.0/common/authservice"
    xmlns:ns3="http://schemas.nav.gov.hu/DCC/1.0/m2m/token/tokenapi">
    <context>
        <requestId>019ce6a6-2a0c-7207-b3f4-cc8373579c7c</requestId>
        <timestamp>2026-03-13T10:02:55.37291704Z</timestamp>
    </context>
    <ns2:auth>
        <ns2:login>m2m_user_example</ns2:login> <1>
        <ns2:passwordHash cryptoType="SHA-512">12B03226A6D8BE9C6E8CD5E55DC6C7920CAAA39DF14AAB92D5E3EA9340D1C8A4D3D0B8E4314F1F6EF131BA4BF1CEB9186AB87C801AF0D5C95B1BEFB8CEDAE2B9</ns2:passwordHash> <2>
        <ns2:taxNumber>12345678</ns2:taxNumber> <3>
        <ns2:predecessorTaxNumber></ns2:predecessorTaxNumber> <4>
        <ns2:requestSignature cryptoType="SHA3-512">6498E406186580DA6403680FD3A6A008FD7F207CA2AFDE5885C38AC700A9A52A3BAADEE914FA0649DBBE103D2D6E99B1236DA403CDD5EF338245A4474770D591</ns2:requestSignature> <5>
    </ns2:auth>
    <ns2:requestVersion>1.0</ns2:requestVersion> <6>
    <ns2:headerVersion>1.0</ns2:headerVersion> <7>
</ns3:M2MTokenRequest>
----
<1> The `login` tag contains the technical user's name.
The login name is randomly generated by the system when creating the technical user, with a length of 15 characters.
The login tag is one of the authentication elements.
<2> The `passwordHash` is the *uppercase* SHA-512 hash of the technical user's password specified in the login tag.
The literal password is set by the primary user who creates the technical user on the Online Invoice web interface.
The passwordHash is one of the authentication elements.
The only accepted value: SHA-512.
<3> The `taxNumber` is the first 8 digits of the tax number of the taxpayer on whose behalf the technical user operates and to whom they belong.
Only Hungarian tax numbers are accepted.
<4> The `predecessorTaxNumber`, if provided, is validated to confirm
whether it has a legal predecessor relationship with the taxpayer specified in the taxNumber tag.
The legal predecessor relationship is checked recursively; indirect legal predecessors are also accepted.
Providing the predecessorTaxNumber affects the business logic of operations.
<5> The `requestSignature` is the client-generated signature of the message.
Every request must have a requestSignature.
The server performs its own requestSignature calculation based on the data in the request and only executes the request
if the correct value can actually be derived from the stored and received data.
The "requestSignature calculation" section provides information about computing the requestSignature.
The only accepted value: SHA3-512.
<6> The `requestVersion` indicates the request version; it is optional - if omitted, the system will use "1.0". Currently only the "1.0" value is accepted.
<7> The `headerVersion` indicates the header version; it is optional - if omitted, the system will use "1.0". Currently only the "1.0" value is accepted.

=== requestSignature calculation
The `requestSignature` is one of the main elements of interface authentication.
Its purpose is to prevent unauthorized parties from making changes in the system.
The hash value is verified by the server side for every request of every operation,
and the operation is only executed if the correct value can actually be derived from the stored and received data.

The `requestSignature` is calculated by concatenating the values of the following fields, in order:

. requestId value (in our case "019ce6a6-2a0c-7207-b3f4-cc8373579c7c")
. the timestamp tag value with the "yyyyMMddHHmmss" mask, in UTC time (in our case "20260313100255")
. the literal value of the technical user's signing key (the value provided when creating the technical user).
For this example, let its value be "ce-8f5e-215119fa7dd621DLMRHRLH2S"

The *uppercase* SHA3-512 hash result of the string concatenated in this order is the `requestSignature` value.

.algorithm
[source,text]
----
requestSignature = SHA3-512(requestId + timestamp + signingKey).UPPERCASE()

requestSignature = SHA3-512(019ce6a6-2a0c-7207-b3f4-cc8373579c7c + 20260313100255 + ce-8f5e-215119fa7dd621DLMRHRLH2S).UPPERCASE()

requestSignature = SHA3-512(019ce6a6-2a0c-7207-b3f4-cc8373579c7c20260313100255ce-8f5e-215119fa7dd621DLMRHRLH2S).UPPERCASE()

requestSignature = 6498e406186580da6403680fd3a6a008fd7f207ca2afde5885c38ac700a9a52a3baadee914fa0649dbbe103d2d6e99b1236da403cdd5ef338245a4474770d591.UPPERCASE()

requestSignature = 6498E406186580DA6403680FD3A6A008FD7F207CA2AFDE5885C38AC700A9A52A3BAADEE914FA0649DBBE103D2D6E99B1236DA403CDD5EF338245A4474770D591
----

== Response: M2MTokenResponse

Upon successful authentication, the response contains the access token and its expiration time.

.M2MTokenResponse XML example
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<ns3:M2MTokenResponse xmlns="http://schemas.nav.gov.hu/NTCA/2.0/common/service" xmlns:ns2="http://schemas.nav.gov.hu/NTCA/2.0/common/authservice"
    xmlns:ns3="http://schemas.nav.gov.hu/DCC/1.0/m2m/token/tokenapi">
    <context>
        <requestId>019ce66a-c965-74cd-9795-1102575b62b7</requestId>
        <timestamp>2026-03-13T08:58:04.006840049Z</timestamp>
    </context>
    <resultCode>SUCCESS</resultCode>
    <ns3:accessToken>eyJhbGciOiJIUzI1NiIsInR5cC... JWT token</ns3:accessToken>
    <ns3:accessTokenExpiryAt>2026-03-13T13:59:07.478552281Z</ns3:accessTokenExpiryAt>
</ns3:M2MTokenResponse>
----

.Response fields
[cols="1,2,1"]
|===
| Field | Description | Type

| `accessToken`
| The access token value to be used for subsequent API calls
| `GenericIdType`

| `accessTokenExpiryAt`
| The token expiration time (UTC, nanosecond precision)
| `GenericTimestampNanoType`
|===

IMPORTANT: The token must be renewed before the expiration time.
Requests sent with an expired token will be rejected.
