name: Generate and publish documentation
on:
  push:
    branches:
      - main

jobs:
  generate-and-publish-docs:
    uses: nav-gov-hu/.github/.github/workflows/WF-mvn-docs.yml@release/0.2.x
    with:
    #   runs-on-os: 'ubuntu-latest'
      java-version: '17'
